spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/gachigage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gachigage123

#  jpa:
#    hibernate:
#      ddl-auto: validate
